### PR TITLE
Use stat for file size, and get output / error in parallel

### PR DESCRIPTION
**Pull request by djw8605**
Here is some changes to your viewOutErr.

1. Use stat instead of running `ls`
2. Perform output and error read operations in parallel

Things you should do:

- [x] Use SFTP streams to read the data.
- [x] Put the output and error in their own boxes, with `<pre>` around them.  Also, the will have to scroll (some HTML work will need to be done here)

### CODE REVIEW

**Comment by djw8605** [comment]
Also, I think I may have broke some of the `result` stuff with jobId and whatnot not showing up anymore.

**Comment by adamfitzgibbon** [comment]
Yeah I was just adding the text to the fetched job object so I'll just add that to your changes to fix the other result stuff. Otherwise those two additional objectives shouldn't be much of a problem and I'll try and resolve them in the couple of hours I'll be in tomorrow morning. Additionally I think I forgot to update the db with the fetched out/err text, so I'll probably do that as well to prevent having to refetch every time the same job is viewed.

**Comment by djw8605** [comment]
That all sounds perfect.

For the page, I would recommend something similar to the main landing page.  IE, a left column of job stats, time took and things like that.  Then a larger column on the right with the output and error.

**Comment by adamfitzgibbon** [comment]
Anything fancy to represent those (other than the scroll boxes for err/out) or is just kind of a list format like I currently have fine?

**Comment by djw8605** [comment]
If you want to get fancy, the left column should be a list somewhat like now.  Though, no list decorators.

For the output/error, I would try maybe collapsable text boxes?  2 bordered text boxes, labeled.  The heading should be like:

    <strong>Output</strong> /full/path/to/output

I'm very open to design options for the actual view.  How to border it... how to have the text box heading look...

**Comment by adamfitzgibbon** [comment]
Okay so when you say collapsable text boxes, I think Bootstrap panels, similar to what I used in the jobHistory page

**Comment by djw8605** [comment]
Yup, bootstrap panels would work.

**Pull request merged**
